function getList() {
  array = [
  ["5 Centimeters Per Second", ""],
  ["A.I.C.O.: Incarnation", ""],
  ["Action Heroine Cheer Fruits", ""],
  ["Agukaru", ""],
  ["Air", ""],
  ["Akira", ""],
  ["A Lull in the Sea", ""],
  ["Amanchu", ""],
  ["Angolmois: Record of Mongol Invasion", ""],
  ["Apache Baseball Army", ""],
  ["A Place Further than the Universe", ""],
  ["Barefoot Gen", ""],
  ["Beyond the Boundary", ""],
  ["Big Order", ""],
  ["Blue Seed", ""],
  ["Bungo Stray Dogs", ""],
  ["Chihayafuru", ""],
  ["Crayon Shin-Chan", ""],
  ["Dagashi Kashi", ""],
  ["Dennou Coil", ""],
  ["Detective Conan", ""],
  ["Diary of our Days at the Breakwater", ""],
  ["Durarara!!", ""],
  ["Eight Clouds Rising", ""],
  ["Encouragement of Climb", ""],
  ["Engaged to the Unidentified", ""],
  ["Erased", ""],
  ["F", ""],
  ["Fate/Zero", ""],
  ["Flying Witch", ""],
  ["Free!", ""],
  ["Gabriel DropOut", ""],
  ["Gegege no Kitarou", ""],
  ["Ghost Hound", ""],
  ["Girls & Panzer", ""],
  ["Girly Air Force", ""],
  ["Glasslip", ""],
  ["Gokujo", ""],
  ["Golden Kamuy", ""],
  ["Good Luck Girl", ""],
  ["Grand Blue", ""],
  ["Grave of the Fireflies", ""],
  ["Ground Control to Psychoelectric Girl", ""],
  ["Gunparade March", ""],
  ["Haikyuu!!", ""],
  ["Hakata Mentai! Pirikarako-chan", ""],
  ["Hakata Tonkotsu Ramens", ""],
  ["Hanasaku Iroha", ""],
  ["Hand Shakers", ""],
  ["Haven’t You Heard? I’m Sakamoto", ""],
  ["Heaven’s Lost Property", ""],
  ["He is My Master", ""],
  ["Her Comes Miss Modern", ""],
  ["Higurashi:When They Cry", ""],
  ["Hikaru no Go", ""],
  ["Hinamatsuri", ""],
  ["Hulaing Babies", ""],
  ["If My Favorite Pop Idol Made It to the Budokan, I Would Die", ""],
  ["Inari Kon Kon", ""],
  ["Initial D", ""],
  ["Iroduku: The World in Colors", ""],
  ["Kamichu!", ""],
  ["Kannagi", ""],
  ["Keijo!!!!!!!!", ""],
  ["Kids on the Slope", ""],
  ["KinMoza", ""],
  ["Komachi to Dangorou", ""],
  ["K-On!", ""],
  ["Kuromukuro", ""],
  ["Lagrange: The Flower of Rin-ne", ""],
  ["Laid-Back Camp", ""],
  ["Laughing Under the Clouds", ""],
  ["Level E", ""],
  ["Looking up at the Half Moon", ""],
  ["Love, Chunibyo & Other Delusions!", ""],
  ["Love Live! Sunshine!!", ""],
  ["Lovely Complex", ""],
  ["Lovely Muco", ""],
  ["Lucky Star", ""],
  ["Madam is a Magical Girl", ""],
  ["Magical Girl Raising Project", ""],
  ["Magical Shopping Arcade Abenobashi", ""],
  ["Mai-Mai Miracle", ""],
  ["Masmamune Datenicle", ""],
  ["Meganebu!", ""],
  ["Mitsuboshi Colors", ""],
  ["Mokke", ""],
  ["Momokuri", ""],
  ["Monkey Turn", ""],
  ["Musashi no Ken", ""],
  ["My Bride is a Mermaid", ""],
  ["My-Hime", ""],
  ["My Mental Choices Are Completely Interfering with my School", ""],
  ["Myself; Yourself", ""],
  ["My Teen Romantic Comedy SNAFU", ""],
  ["Napping Princess", ""],
  ["Natsume’s Book of Friends", ""],
  ["Natsunagu!", ""],
  ["Neon Genesis Evangelion", ""],
  ["Non Non Biyori", ""],
  ["No-Rin", ""],
  ["Ocean Waves", ""],
  ["Oi! Ryoma", ""],
  ["Onegai Teacher", ""],
  ["Only Yesterday", ""],
  ["Persona 4", ""],
  ["Poco’s Udon World", ""],
  ["Prefectural Earth Defense Force", ""],
  ["Princess Mononoke", ""],
  ["RDG: Red Data Girl", ""],
  ["Robotics;Notes", ""],
  ["Saki", ""],
  ["Sakura no Chikai:Maronni Yell", ""],
  ["Sakura Quest", ""],
  ["Sarazanmai", ""],
  ["Shrine of the Morning Mist", ""],
  ["Silverfang", ""],
  ["Silver Spoon", ""],
  ["Sketchbook: Full Color’s", ""],
  ["Slam Dunk", ""],
  ["Sound! Euphonium", ""],
  ["Space Brothers", ""],
  ["Spring and Chaos", ""],
  ["Steins;Gate", ""],
  ["Strawberry Marshmallow", ""],
  ["Tamako Market", ""],
  ["Tamayura", ""],
  ["Tari Tari", ""],
  ["Teasing Master Takagi", ""],
  ["Tenchi Muyou!", ""],
  ["The Eccentric Family", ""],
  ["The Flowers of Evil", ""],
  ["The Lost Village", ""],
  ["The Melancholy of Haruhi Suzumiya", ""],
  ["The Place Promised in our Early Days", ""],
  ["The Tatami Galaxy", ""],
  ["The Wind Rises", ""],
  ["The Wings of Rean", ""],
  ["True Tears", ""],
  ["Umi Monogatari", ""],
  ["Ushio to Tora", ""],
  ["Waiting in the Summer", ""],
  ["Wake Up, Girls!", ""],
  ["Wave, Listen to Me!", ""],
  ["Wolf Children", ""],
  ["Working!!", ""],
  ["Yaoamushi Pedal", ""],
  ["Yatogame-chan Kansatsu", ""],
  ["Yomigaeru Sora: Rescue Wings", ""],
  ["Your Name", ""],
  ["Yukiwatari", ""],
  ["Yuki Yuna is a Hero", ""],
  ["Yuri!!! On Ice", ""],
  ["Zombieland Saga", ""]]
  

  renderList(array)
}

function renderList(arr) {
  table = document.getElementById("animeList");
  count = 4;
  for (i=0; i < arr.length / count; i++) {
    row = document.createElement("tr");
    for (j = 0; j < count; j++) {
    td = document.createElement("td");
      link = document.createElement("a");
      link.setAttribute("href",arr[i+j][1]);
      link.innerHTML = arr[i+j][0];
      td.appendChild(link);
      if (arr[i+j] != null) {
      row.appendChild(td);
      }
    }
    row.appendChild(td);
    table.appendChild(row);
  }
  console.log(table);
}


getList()
